---
title: "TUP usage statistics"
---

Reproduction of analysis published in Snijder, R., 2023. Measured in a context: making sense of open access book data. Insights: the UKSG journal, 36(1), p.20. [https://doi.org/10.1629/uksg.627](https://doi.org/10.1629/uksg.627)


Data downloaded from [https://doi.org/10.5281/zenodo.7799222](https://doi.org/10.5281/zenodo.7799222).

```{r setup, echo=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(magrittr)
library(data.table)
library(here)
```

```{r load-data, echo=FALSE, message=FALSE}
oapen <- data.table::fread(here::here('data','TOANI_data_OAPEN Library_202201-202212.csv'))

```

```{r tup_data, echo=FALSE, message=FALSE}
tup_2020 <- data.table::fread(here::here("data","tampere-university-press-202001-202012.csv"))
tup_2021 <- data.table::fread(here::here("data","tampere-university-press-202101-202112.csv"))
tup_2022 <- data.table::fread(here::here("data","tampere-university-press-202201-202212.csv"))
tup_2023 <- data.table::fread(here::here("data","tampere-university-press-202301-202312.csv"))

tup_thema <- data.table::fread("/Users/ccmala/Documents/2023/tup-books/tup-books-to-omp-thema.csv")
```



```{r clean-oapen-dataset, echo=FALSE}
oapen[oapen == ""] <- NA 
colnames(oapen) <- tolower(stringr::str_replace_all(colnames(oapen),"-","_"))

oapen_orig <- oapen

oapen[oapen$language_simple == "720",]$q4 <- 720
oapen[oapen$language_simple == "720"]$language_simple <- "Other"

err_rows <- oapen %>% filter(classification=="Total_Item_Requests")

oapen %<>% anti_join(err_rows, by="uri")
oapen %<>% mutate(
  total_2022 = as.numeric(total_2022))
```

```{r prepare-data, echo=FALSE}
# Lets rename some fields

oapen %<>% mutate(titles_in_lang_subject_grp = total) %>% select(-total)
oapen %<>% mutate(
  id = stringr::str_replace(uri,"library.oapen.org/handle/",""),
  min = q0,
  max = q4,
  median = q2,
  first_quantile = q1,
  third_quantile = q3
  ) %>%
  select(
    -q0,
    -q1,
    -q2,
    -q3,
    -q4)

vars_to_select <- c(
  "titles_in_lang_subject_grp",
  "min",
  "max",
  "median",
  "first_quantile",
  "third_quantile"
)

oapen_downloads_per_group <- oapen %>% select(all_of(vars_to_select),classification) %>% distinct_all

toani_gold_standard <- oapen %>% select(uri,toani_score)
oapen %<>% select(-all_of(vars_to_select)) %>% select(-toani_score)




```

```{r clean-tup-data, echo=FALSE}

tup_columns <- c("id","total")


tup_2020 %<>% select(all_of(tup_columns)) %>% mutate(year=2020)
tup_2021 %<>% select(all_of(tup_columns)) %>% mutate(year=2021)
tup_2022 %<>% select(all_of(tup_columns)) %>% mutate(year=2022)
tup_2023 %<>% select(all_of(tup_columns)) %>% mutate(year=2023)

tup_downloads <- bind_rows(
  tup_2020,
  tup_2021,
  tup_2022,
  tup_2023
)

tup_downloads %<>% inner_join(oapen %>% select(id,classification), by="id")

```

```{r tables-setup, echo = FALSE}
col_headers <- c(
  "Subject",
  "N",
  "Min",
  "Max",
  "Median downloads",
  "Total downloads"
)


```


## Data from Snijder, R., 2023

```{r oapen-downloads-published-data, echo=FALSE}
oapen_downloads_per_group %<>% relocate(classification,titles_in_lang_subject_grp,min,max,median)

knitr::kable(
  oapen_downloads_per_group %>% 
    select(
      -first_quantile,
      -third_quantile),
  #col.names = col_headers,
  caption = "OAPEN Library titles by language and subject",
  col.names = c("Subject","N","Min","Max","Median")
  
  )
```



```{r oapen-titles-by-language-and-subject, echo=FALSE, message=FALSE}
knitr::kable(oapen %>% 
  group_by(classification, language_simple) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    median_downloads = median(total_2022),
    total_downloads = sum(total_2022)
    ) %>% distinct_all,
    col.names = c("Subject","Language","N","Median","Total"),
    caption = "OAPEN Library titles by language and subject, using cleaned dataset")

```



```{r tup-comparison, echo = FALSE}

tup_fin <- oapen %>% filter(publisher == "Tampere University Press", language == "Finnish")
tup_eng <- oapen %>% filter(publisher == "Tampere University Press", language == "English")

noasp_nor <- oapen %>% 
  filter(
    publisher == "Cappelen Damm Akademisk/NOASP (Nordic Open Access Scholarly Publishing)",
    language != "English") 





```

## Comparing publishers

Published OAPEN data: [Cappelen Damm Akademisk/NOASP](https://press.nordicopenaccess.no/index.php/noasp) 2022

```{r publishing-profile-noasp, message=FALSE, echo=FALSE}
knitr::kable(noasp_nor %>% 
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total_2022),
    max = max(total_2022),
    median_downloads = median(total_2022),
    total_downloads = sum(total_2022)
    ) %>% distinct_all,
    col.names = col_headers,
    caption = "Year 2022 downloads per subject group, items published by NOASP")
```


Published OAPEN data: Tampere University Press 2022

```{r publishing-profile-tup-published-data, message=FALSE, echo=FALSE}
knitr::kable(tup_fin %>% 
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total_2022),
    max = max(total_2022),
    median_downloads = median(total_2022),
    total_downloads = sum(total_2022)
    ) %>% distinct_all,
    col.names = col_headers,
    caption = "Year 2022 downloads per subject group, items published by TUP")
```

## Data from publisher statistics dashboard

```{r publishing-profile-tup-2020, message=FALSE, echo=FALSE}
knitr::kable(tup_downloads %>% 
  filter(year == 2020) %>%
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total),
    max = max(total),
    median_downloads = median(total),
    total_downloads = sum(total)
    ) %>% distinct_all,
    col.names = col_headers,
    caption = "Year 2020 downloads per subject group, items published by TUP")
```


```{r publishing-profile-tup-2021, message=FALSE, echo=FALSE}
knitr::kable(tup_downloads %>% 
  filter(year == 2021) %>%
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total),
    max = max(total),
    median_downloads = median(total),
    total_downloads = sum(total)
    ) %>% distinct_all,
    col.names = col_headers,
    caption = "Year 2021 downloads per subject group, items published by TUP")
```


```{r publishing-profile-tup-2022, message=FALSE, echo=FALSE}
knitr::kable(tup_downloads %>% 
  filter(year == 2022) %>%
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total),
    max = max(total),
    median_downloads = median(total),
    total_downloads = sum(total)
    ) %>% distinct_all,
    col.names = col_headers,
    caption = "Year 2021 downloads per subject group, items published by TUP")
```


```{r publishing-profile-tup-2023, message=FALSE, echo=FALSE}
knitr::kable(tup_downloads %>% 
  filter(year == 2023) %>%
  group_by(classification) %>%
  mutate(n = n()) %>%
  summarize(
    number_of_titles = n,
    min = min(total),
    max = max(total),
    median_downloads = median(total),
    total_downloads = sum(total)
    ) %>% distinct_all,
  col.names = col_headers,
  caption = "Year 2023 downloads per subject group, items published by TUP")
```





